server:
  port: 9595

spring:
  application:
    name: cluod-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/onerogun/cloudconfiguration
          force-pull: true

