version: '3.5'
services:

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"


  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=ogn
      - MYSQL_PASSWORD=ogn
    ports:
      - "3307:3306"
    volumes:
      - .datadir:/var/lib/mysql


