version: '3.5'
services:


  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  cloud-config-server:
    image: cloud-config-server:0.0.1-SNAPSHOT
    depends_on:
      - zipkin

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=ogn
      - MYSQL_PASSWORD=ogn
    ports:
      - "3307:3306"
    volumes:
      - .datadir:/var/lib/mysql
    depends_on:
      - cloud-config-server

  discovery-server:
    image: discovery-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    depends_on:
      - cloud-config-server

  cloud-gateway:
    image: cloud-gateway:0.0.1-SNAPSHOT
    ports:
      - "9191:9191"
    depends_on:
      - discovery-server
      - cloud-config-server

  customer-service:
    image: customer-service:0.0.1-SNAPSHOT
    depends_on:
      - discovery-server
      - cloud-config-server
      - mysqldb

  item-service:
    image: item-service:0.0.1-SNAPSHOT
    depends_on:
      - discovery-server
      - cloud-config-server
      - mysqldb

  order-service:
    image: order-service:0.0.1-SNAPSHOT
    depends_on:
      - discovery-server
      - cloud-config-server
      - mysqldb

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - .prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - discovery-server
      - cloud-gateway



