name: chat-server CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permisson to mvnw
        run: chmod +x mvnw

      - name: Build image with Maven
        run: ./mvnw spring-boot:build-image

      - name: run docker push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag chat-server:0.0.1-SNAPSHOT ogunfz09/chat-server
          docker push ogunfz09/chat-server
