spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        signinalert:
          destination: newsigninalert
        passwordreset:
          destination: passwordresetmail

